spring:
  application:
    name: quartz
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quartz?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456